### ISSUE TITLE
React Capstone Project

### ISSUE THREAD

**Issue by Lucas-Erkana** [Lucash2022/React-Group-Project#26]
[Link to Kanban](https://github.com/Lucash2022/React-Group-Project/projects/1)
We are a team of 2.

@Lucash2022 
@stevenmukama

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @Lucash2022 and @stevenmukama , 

To highlight 👍🏽 
✔️ You added your project link
✔️ All tasks are equally assigned
✔️ All cards for a team of 3 have been removed

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- I suggest you also close all issues for team 3 since you are a team of 2. This would help your codebase be neater and more professional

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
